name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build book
        run: jupyter-book build ./rca_qaqc_reports
      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f ./rca_qaqc_reports/_build/html